### ISSUE TITLE
NPE while synchronising

### ISSUE THREAD

**Issue by s-seidel** [gnl42/JiraConnector#41]
Getting a sync error:
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:556)
	at java.base/java.util.List.of(List.java:812)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.generateCustomField(JiraRestConverter.java:526)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.getCustomFieldsFromIssue(JiraRestConverter.java:380)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.convertIssue(JiraRestConverter.java:160)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter$4.call(JiraRestClientAdapter.java:315)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter$4.call(JiraRestClientAdapter.java:1)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:765)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.getIssues(JiraRestClientAdapter.java:300)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:358)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:351)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.search(JiraClient.java:731)
	at me.glindholm.connector.eclipse.internal.jira.core.JiraRepositoryConnector.performQuery(JiraRepositoryConnector.java:144)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:306)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:263)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:194)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

It's probably related to this warning, which shows up a lot:
```
Unable extract value for field [security:Security Level:SecurityLevel [id=10005, description=Vorgänge, welche nur intern und X angezeigt werden sollen., AddressableNamedEntity [self=https://instancename.atlassian.net/rest/api/2/securitylevel/10005, name=Intern + X]]].
```

**Comment by gnl42** [comment]
Hi,
   that error message should be benign. 
The point where the error is occuring has nothing to do with an unknown field so I'm at a loss as to what is happening here.

Can you tell me how the issue has been set up? Any special attributes? security levels?

Could you send me the raw output from ${jira server}/rest/api/latest/issue/${issue}?expand=renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations
(blanking any sensitive information)

Thanks

**Comment by s-seidel** [comment]
I hope I blanked out enough and not too much and that this issue is a problematic one. It is very similar to other issues on the board.
[issue.json.gz](https://github.com/gnl42/JiraConnector/files/10031595/issue.json.gz)

**Comment by s-seidel** [comment]
Oh, forgot to say that we are using a customer's JIRA instance and we do not have control over it and have not set it up, but we have the impression that not everything is set up in a good way.

**Comment by gnl42** [comment]
Thanks, that should help.

Can you also send the output from `${jira server}/rest/api/latest/serverInfo`

**Comment by s-seidel** [comment]
It's JIRA Cloud:
```
{
  "baseUrl": "https://mycompany.atlassian.net",
  "version": "1001.0.0-SNAPSHOT",
  "versionNumbers": [
    1001,
    0,
    0
  ],
  "deploymentType": "Cloud",
  "buildNumber": 100210,
  "buildDate": "2022-11-15T23:25:58.000+0100",
  "serverTime": "2022-11-17T14:46:55.120+0100",
  "scmInfo": "9b34d7cc56ccedf37042f403595483f2079121f4",
  "serverTitle": "Jira",
  "defaultLocale": {
    "locale": "de_DE"
  }
}
```

**Comment by gnl42** [comment]
Thanks, I thought so. I just have the developer cloud version, and I gather that the security features needs another version so it complicates this slightly.

What version of the plugin do you have?

**Comment by gnl42** [comment]
Does the field show when you view the ticket in your browser?

**Comment by s-seidel** [comment]
> JiraConnector for Eclipse	4.1.7.v20220721-0406	me.glindholm.connector.eclipse.feature.group	George Lindholm

The security level does show in the browser, however, it doesn't really look like a field:

![image](https://user-images.githubusercontent.com/87427198/202644194-29c6f8cf-1753-4233-8714-4f4e71b0ce1c.png)

**Comment by gnl42** [comment]
Could you try:
`Task Repositories view->${jira server}->Update Repository Configuration`
then refresh the ticket

**Comment by s-seidel** [comment]
I already did that a couple of times and it does seem to work, but there are no tickets synchronised at all.

**Comment by gnl42** [comment]
Hi, I just pushed a new version out that should fix the warnings about SecurityLevel. I have no idea if will fix the exception you're seeing.

Please try it out and let me know if it helps. If not, please post an updated error stacktrace and I'll take another stab at it.

Thanks
George

**Comment by s-seidel** [comment]
Thanks. The SecurityLevel warning is now gone, but instead I get `Unable extract value for field [customfield_10033:Request language:{"languageCode":"de","displayName":"German"}].` I guess a more generalized solution would be needed there? The sync error is the same with the same stack trace.

**Comment by gnl42** [comment]
I've thought about it in the past, unfortunately in this case it won't help since the field seems to be provided by a third party plugin and the values for it doesn't follow the standard format.

Can you send me the new stack trace since I made some changes in the area where it blows and I need to see where the error moved to? Thanks

**Comment by s-seidel** [comment]
Thanks for your efforts. This is the new stracktrace:
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:556)
	at java.base/java.util.List.of(List.java:812)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.generateCustomField(JiraRestConverter.java:501)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.getCustomFieldsFromIssue(JiraRestConverter.java:376)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.convertIssue(JiraRestConverter.java:163)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter$4.call(JiraRestClientAdapter.java:317)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter$4.call(JiraRestClientAdapter.java:1)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:771)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.getIssues(JiraRestClientAdapter.java:302)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:358)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:351)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.search(JiraClient.java:731)
	at me.glindholm.connector.eclipse.internal.jira.core.JiraRepositoryConnector.performQuery(JiraRepositoryConnector.java:144)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:306)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:263)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:194)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

And what about ignoring those custom fields? Might be at least better than failing completely.

**Comment by gnl42** [comment]
Ok, that stacktrace makes more sense. 
It seems you have a field: either "Approvers" or "Ansprechpartner", that isn't sending the plugin the information expected.

The custom field complaints is just a warning, it doesn't fail the synch.

I just pushed out 4.1.9 that should fix your problem

**Comment by s-seidel** [comment]
Wohoo, great. It syncs now. Thanks heaps!
