### ISSUE TITLE
404: Issue Does Not Exist

### ISSUE THREAD

**Issue by Holzhauer** [gnl42/JiraConnector#45]
I can successfully connect to the JIRA server, also update the project listing successfully, but when clicking "Finish" when creating a new task I get the "404: Issue Does Not Exist" message. Also when I synchronize a task query I get "404: Issue Does Not Exist".

**Comment by karacz** [comment]
I am having the same issue
- JIRA - Jira 9.0#900003 (2022-06-20)
- plugin - JiraConnector 4.1.8
```
me.glindholm.connector.eclipse.internal.jira.core.service.JiraException: me.glindholm.connector.eclipse.internal.jira.core.service.JiraException: java.util.concurrent.ExecutionException: RestClientException{statusCode=Optional[404], ErrorCollections=[ErrorList [status=404, errorMessages=[Issue Does Not Exist], errors={}]]}
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:821)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.getIssues(JiraRestClientAdapter.java:296)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:377)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.search(JiraClient.java:764)
	at me.glindholm.connector.eclipse.internal.jira.core.JiraRepositoryConnector.performQuery(JiraRepositoryConnector.java:144)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:306)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:263)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:194)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: me.glindholm.connector.eclipse.internal.jira.core.service.JiraException: java.util.concurrent.ExecutionException: RestClientException{statusCode=Optional[404], ErrorCollections=[ErrorList [status=404, errorMessages=[Issue Does Not Exist], errors={}]]}
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.getProjectDetails(JiraRestClientAdapter.java:353)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.getProjectDetails(JiraClient.java:674)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClientCache.initializeProject(JiraClientCache.java:89)
	at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClientCache.refreshProjectDetails(JiraClientCache.java:284)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.convertIssue(JiraRestConverter.java:174)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter$4.call(JiraRestClientAdapter.java:311)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter$4.call(JiraRestClientAdapter.java:1)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:776)
	... 8 more
Caused by: java.util.concurrent.ExecutionException: RestClientException{statusCode=Optional[404], ErrorCollections=[ErrorList [status=404, errorMessages=[Issue Does Not Exist], errors={}]]}
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.atlassian.util.concurrent.Promises$OfStage.get(Promises.java:353)
	at me.glindholm.jira.rest.client.internal.async.DelegatingPromise.get(DelegatingPromise.java:101)
	at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.getProjectDetails(JiraRestClientAdapter.java:341)
	... 15 more
Caused by: RestClientException{statusCode=Optional[404], ErrorCollections=[ErrorList [status=404, errorMessages=[Issue Does Not Exist], errors={}]]}
	at me.glindholm.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:156)
	at me.glindholm.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:1)
	at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:49)
	at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:10)
	at io.atlassian.util.concurrent.Promises$OfStage.lambda$fold$4(Promises.java:332)
	at io.atlassian.util.concurrent.Promises.lambda$biFunction$7(Promises.java:422)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1.lambda$doCompleted$0(SettableFuturePromiseHttpPromiseAsyncClient.java:37)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:61)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:129)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by gnl42** [comment]
Sigh, JiraServer 9 removed an API end point

Fixed with 4.3.0

**Comment by Holzhauer** [comment]
Working well. Thanks a lot!

**Comment by gnl42** [comment]
Glad to hear that
