### ISSUE TITLE
Strange ClassCastException when trying to load Jira issues

### ISSUE THREAD

**Issue by whustedt** [gnl42/JiraConnector#57]
```
java.lang.ClassCastException: class org.codehaus.jettison.json.JSONArray cannot be cast to class org.codehaus.jettison.json.JSONArray (org.codehaus.jettison.json.JSONArray is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @3a5f8888; org.codehaus.jettison.json.JSONArray is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @38436696)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestCustomFieldsParser.parseMultiUserPicker(JiraRestCustomFieldsParser.java:43)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.generateCustomField(JiraRestConverter.java:510)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.getCustomFieldsFromIssue(JiraRestConverter.java:398)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.convertIssue(JiraRestConverter.java:167)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.lambda$3(JiraRestClientAdapter.java:294)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:743)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.getIssues(JiraRestClientAdapter.java:281)
        at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:374)
        at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.search(JiraClient.java:756)
        at me.glindholm.connector.eclipse.internal.jira.core.JiraRepositoryConnector.performQuery(JiraRepositoryConnector.java:143)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:306)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:263)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:194)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### Details about Installation
- eclipse.buildId=4.29.0.20230907-1200
- java.version=17.0.8.1
- java.vendor=Eclipse Adoptium
- BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
- Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
- Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -data file:/C:/Entwicklung/20231122_eclipse-workspace-202309/ -product org.eclipse.epp.package.java.product

**Comment by gnl42** [comment]
Hi, sorry about that. I didn't realize keeping the older version around would create such havoc.

Try it now

George

**Comment by whustedt** [comment]
Hi, thanks for the quick response. 
Unfortunately, I am still getting the same error even after updating to version 5.0.0.v20240129-0811.
Wilken

**Comment by gnl42** [comment]
Hmm, you may have the old version install as well.

See if you have JiraConnector installed:

`Help -> About Eclipse IDE => Installation Details`

Uninstall the plugin if you see it there and retry installing 5.0.0

George

**Comment by whustedt** [comment]
Hi George,

I've checked and confirmed no other JiraConnector versions in Eclipse (screenshot attached). I assume plugins should not interfere with each other. Still, I'm facing issues with version 5.0.0. Any other suggestions?

![Eclipse Installation Details](https://github.com/gnl42/JiraConnector/assets/3454347/cd92ccf8-54eb-4d33-b047-839860fa914c)

Thanks,

Wilken
