### ISSUE TITLE
Cannot update task list

### ISSUE THREAD

**Issue by zxfr** [gnl42/JiraConnector#66]
Hi! I just installed the latest build of Eclipse, hoping that Jira+Mylyn is finally back in order again.
Unfortunately it still cannot update the task list, although now it fails silently without popping up an error message box.

To troubleshoot I created `.options` with the content 
```
org.eclipse.mylyn.jira.core/debug/connector=true
org.eclipse.mylyn.jira.core/debug/dataHandler=true
org.eclipse.mylyn.jira.core/debug/repository=true
```
in the `eclipse/` dir, run Eclipse with `-debug` parameter and was able to capture the exception:

```
java.lang.NullPointerException: Cannot invoke "me.glindholm.jira.rest.client.api.domain.BasicWatchers.isWatching()" because "watched" is null
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestConverter.convertIssue(JiraRestConverter.java:322)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.lambda$3(JiraRestClientAdapter.java:294)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:743)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.getIssues(JiraRestClientAdapter.java:281)
        at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:374)
        at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:367)
        at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.search(JiraClient.java:754)
        at me.glindholm.connector.eclipse.internal.jira.core.JiraRepositoryConnector.performQuery(JiraRepositoryConnector.java:143)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:307)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:264)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:195)
```

I hope this information will help solve the issue. I look forward to it. Thanks in advance!

**Comment by gnl42** [comment]
Hi, nice catch. I'll try and get a fix out tonight

**Comment by gnl42** [comment]
Fixed with 5.1.3

Not sure why watchers would not be allowed, but ...

**Comment by zxfr** [comment]
Thank you! It seems to be working now.

> Not sure why watchers would not be allowed, but ...

I vaguely remember something... I try to periodically (probably every six months) revive Mylyn and each time I encountered new failures. And one of them was constant errors in the background sync process - maybe then I disabled these watchers in the settings.

It is also worth noting that after today's update Mylyn did not work right away - it began to freeze at 0%, sometimes at 100% progress, and the task list was never updated.

In `options->Mylyn->Tasks->Advanced` I changed `Data directory`. It asked for confirmation, but in fact it did not change the directory as requested. At least it re-init the local cache. Now the task list is in sync. 

Thank you for your help and the quickest possible turnaround with the bugfix!

**Comment by zxfr** [comment]
This one seems to be harmless, but in the next attack of perfectionism (if there is one) it can also be handled:

```
org.eclipse.core.runtime.OperationCanceledException
        at org.eclipse.core.runtime.SubMonitor$RootInfo.checkForCancellation(SubMonitor.java:317)
        at org.eclipse.core.runtime.SubMonitor.split(SubMonitor.java:1127)
        at org.eclipse.core.runtime.SubMonitor.split(SubMonitor.java:1021)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.lambda$3(JiraRestClientAdapter.java:290)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:743)
        at me.glindholm.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.getIssues(JiraRestClientAdapter.java:281)
        at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:374)
        at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:367)
        at me.glindholm.connector.eclipse.internal.jira.core.service.JiraClient.search(JiraClient.java:754)
        at me.glindholm.connector.eclipse.internal.jira.core.JiraRepositoryConnector.performQuery(JiraRepositoryConnector.java:143)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:307)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:264)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:195)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeRepositoriesJob.updateQueries(SynchronizeRepositoriesJob.java:192)
        at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeRepositoriesJob.run(SynchronizeRepositoriesJob.java:147)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
